default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary: &primary_config
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: rails_db_5wxe
    username: rails_db_5wxe_user
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: dpg-cut2aflumphs73cektng-a
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

  cable:
    <<: *primary_config

  queue:
    <<: *primary_config

  cache:
    <<: *primary_config
